services:
  web:
    build: .
    ports: ["8000:8000"]
    environment:
      - DEBUG=1
      - ALLOWED_HOSTS=*
      - PAGE_SIZE=24
      - CACHE_TTL=3600
    volumes:
      - .:/app
    command: >
      gunicorn pokedex_project.wsgi:application
      --bind 0.0.0.0:8000
      --workers 3
      --timeout 120
